# Generated by Django 4.2.1 on 2023-06-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_payment', models.CharField(db_index=True, max_length=50, verbose_name='Форма оплаты')),
            ],
            options={
                'verbose_name': 'форму оплаты',
                'verbose_name_plural': 'Форма оплаты',
                'db_table': 'form_payment',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(db_index=True, max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('gender', models.IntegerField(choices=[(0, '---------'), (1, 'Мужчина'), (2, 'Женщина')], default=0, verbose_name='Пол')),
                ('INN', models.PositiveBigIntegerField(null=True, unique=True, verbose_name='ИНН')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('name_telegram', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ник telegram')),
                ('status1', models.BooleanField(default=False, verbose_name='Принят на работу')),
                ('job_date', models.DateField(blank=True, null=True, verbose_name='Принят на работу, дата')),
                ('status2', models.BooleanField(default=False, editable=False, verbose_name='На доставке')),
                ('salary', models.IntegerField(verbose_name='Оклад/Оплата')),
                ('about_me', models.TextField(verbose_name='О сотруднике')),
                ('form_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.formpayment', verbose_name='Форма оплаты')),
                ('job', models.ManyToManyField(to='employees.professions', verbose_name='Должность')),
                ('restaurant', models.ManyToManyField(to='organizations.restaurantaddresses', verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'сотрудника',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
    ]
