# Generated by Django 4.2.1 on 2023-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города обслуживания',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='RestaurantAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_addresse', models.CharField(db_index=True, max_length=250, verbose_name='Адрес ресторана')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'Адреса ресторанов',
                'db_table': 'restaurant_addresses',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.CharField(choices=[('IP', 'ИП'), ('OOO', 'ООО')], default='IP', max_length=3, verbose_name='Форма регистрации')),
                ('name_restaurant', models.CharField(blank=True, max_length=50, verbose_name='Название ресторана')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('INN', models.PositiveBigIntegerField(verbose_name='ИНН')),
                ('OGRN', models.PositiveBigIntegerField(verbose_name='ОГРН')),
                ('phone1', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('restaurant', models.ManyToManyField(to='organizations.restaurantaddresses', verbose_name='Адреса ресторанов')),
            ],
            options={
                'verbose_name': 'организацию',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
            },
        ),
    ]
